/* ============================================================
   Duet — curated Google Fonts pairing data
   Every family here is verified available on fonts.google.com.
   P(heading, body, category, useCase, note, opts?)
   opts.hw = heading weight override (default 700)
   ============================================================ */

const CATEGORIES = {
  "all":         "All",
  "serif-sans":  "Serif × Sans",
  "sans-serif":  "Sans × Serif",
  "sans-sans":   "Sans × Sans",
  "serif-serif": "Serif × Serif",
  "display":     "Display",
  "slab":        "Slab",
  "mono":        "Mono",
  "script":      "Script",
};

/* Families that ship in a single 400 weight on Google Fonts */
const SINGLE_400 = new Set([
  "Abril Fatface","ABeeZee","Alfa Slab One","Anton","Archivo Black","Bebas Neue",
  "Bungee","Calistoga","Crete Round","Fjalla One","Gloock","Great Vibes",
  "Instrument Serif","Italiana","Julius Sans One","Krona One","Libre Caslon Display",
  "Marcellus","Monoton","Pacifico","Parisienne","Patrick Hand","Patua One",
  "Poiret One","Prata","Righteous","Rozha One","Sacramento","Satisfy",
  "Shadows Into Light","Shrikhand","Six Caps","Sorts Mill Goudy","Staatliches",
  "Ultra","Yellowtail","Yeseva One","Young Serif",
]);

/* Families with a limited weight range (no 700) */
const LIMITED_WEIGHTS = { "DM Mono": [400, 500] };

const SERIF_FAMILIES = new Set([
  "Playfair Display","Lora","Merriweather","Fraunces","DM Serif Display","DM Serif Text",
  "Libre Baskerville","Cormorant Garamond","EB Garamond","Prata","Yeseva One","Italiana",
  "Marcellus","Cinzel","Bodoni Moda","Spectral","Newsreader","Literata","Source Serif 4",
  "IBM Plex Serif","PT Serif","Alegreya","Noto Serif","Roboto Serif","Instrument Serif",
  "Young Serif","Gloock","Vollkorn","Cardo","Frank Ruhl Libre","Old Standard TT",
  "Sorts Mill Goudy","Eczar","Gelasio","Crimson Pro","Crimson Text","Libre Caslon Display",
  "Libre Caslon Text","Abril Fatface","Ultra","Rozha One","Alfa Slab One","Patua One",
  "Roboto Slab","Arvo","Zilla Slab","Bitter","Domine","Rokkitt","Crete Round","Aleo",
  "Josefin Slab","Calistoga","Shrikhand",
]);

const MONO_FAMILIES = new Set([
  "Space Mono","IBM Plex Mono","JetBrains Mono","Fira Code","Source Code Pro","Roboto Mono",
  "DM Mono","Inconsolata","Courier Prime","Martian Mono","Azeret Mono","Chivo Mono",
  "Red Hat Mono","Spline Sans Mono","Geist Mono","Ubuntu Mono","Overpass Mono",
]);

const SCRIPT_FAMILIES = new Set([
  "Caveat","Pacifico","Dancing Script","Great Vibes","Sacramento","Parisienne","Amatic SC",
  "Shadows Into Light","Satisfy","Kalam","Patrick Hand","Yellowtail",
]);

/* Headline display-size boost for condensed / script faces */
const SIZE_BOOST = {
  "Bebas Neue":1.30,"Anton":1.22,"Six Caps":1.55,"Fjalla One":1.18,"Staatliches":1.25,
  "Teko":1.35,"Oswald":1.12,"Bungee":1.05,"Passion One":1.15,"Archivo Black":1.02,
  "Barlow Condensed":1.2,"Yanone Kaffeesatz":1.2,
  "Caveat":1.3,"Dancing Script":1.18,"Pacifico":1.08,"Great Vibes":1.35,"Sacramento":1.4,
  "Parisienne":1.28,"Yellowtail":1.2,"Satisfy":1.2,"Shadows Into Light":1.2,"Amatic SC":1.45,
  "Kalam":1.1,"Patrick Hand":1.15,"Italiana":1.12,"Monoton":1.0,
};

function P(h, b, c, use, note, opts = {}) {
  return { h, b, c, use, note, hw: opts.hw || 700 };
}

const PAIRINGS = [

/* ── SERIF HEADINGS × SANS BODY ─────────────────────────────── */
P("Playfair Display","Source Sans 3","serif-sans","Editorial","The canonical editorial pairing of the last decade — Didone drama up top, plain-spoken humanist text below."),
P("Playfair Display","Lato","serif-sans","Magazine","High-contrast elegance over warm, friendly text. A magazine masthead in two clicks."),
P("Playfair Display","Raleway","serif-sans","Fashion","Both faces have thin, refined strokes — together they read effortlessly upscale."),
P("Playfair Display","Montserrat","serif-sans","Luxury","Old-world serif meets geometric modernity. One of the most-used duos on the web, for good reason."),
P("Playfair Display","Chivo","serif-sans","Editorial","A Typewolf favourite — Chivo's grotesque sturdiness keeps Playfair's flourish grounded."),
P("Lora","Roboto","serif-sans","Blog","Lora's brushed curves soften Roboto's engineering. The default recipe for a readable, trustworthy blog."),
P("Lora","Open Sans","serif-sans","Blog","Two of Google Fonts' most battle-tested families. Zero risk, all comfort."),
P("Lora","Mulish","serif-sans","Health","Gentle contrast and open counters — calm, clinical, and kind."),
P("Merriweather","Montserrat","serif-sans","News","A newsroom staple: sturdy slab-ish serif headlines with clean geometric support text."),
P("Merriweather","Open Sans","serif-sans","Blog","The classic WordPress-era combo. Screen-first serif over the web's most neutral sans."),
P("Merriweather","Merriweather Sans","serif-sans","News","A true superfamily — designed together, so x-heights and rhythm match perfectly."),
P("Fraunces","Inter","serif-sans","Brand","The 2020s brand look: a soft, wonky revival serif against dead-neutral UI text."),
P("Fraunces","Poppins","serif-sans","Food","Fraunces' buttery curves with Poppins' round geometry — warm, appetising, contemporary.",{hw:600}),
P("Fraunces","Manrope","serif-sans","SaaS","Friendly fintech energy: characterful headlines, engineered body text.",{hw:600}),
P("DM Serif Display","DM Sans","serif-sans","Brand","Designed as siblings by Colophon Foundry — sharing DNA, they can't clash."),
P("DM Serif Display","Poppins","serif-sans","Fashion","Sharp Didone display with soft geometric text. Beauty-brand ready."),
P("DM Serif Text","Figtree","serif-sans","Blog","A quieter take on the DM look — text-sized serif over a friendly modern grotesque."),
P("Libre Baskerville","Montserrat","serif-sans","Editorial","Book-grade tradition against crisp geometry. Serious content, modern frame."),
P("Libre Baskerville","Source Sans 3","serif-sans","Education","Scholarly without being stuffy. Excellent for long-form learning material."),
P("Cormorant Garamond","Montserrat","serif-sans","Luxury","Featherweight garalde display over solid geometric text — the boutique-hotel look.",{hw:600}),
P("Cormorant Garamond","Fira Sans","serif-sans","Architecture","Delicate serif detail balanced by Fira's technical clarity.",{hw:600}),
P("EB Garamond","Montserrat","serif-sans","Fashion","Five centuries of typographic pedigree, styled with a modern wardrobe."),
P("EB Garamond","Inter","serif-sans","Education","Classical text at display size, UI-grade sans below. Understated and smart."),
P("Prata","Lato","serif-sans","Luxury","Prata's Didone sparkle needs a quiet partner — Lato disappears politely."),
P("Prata","Work Sans","serif-sans","Architecture","High-contrast elegance over a no-nonsense workhorse. Property brochures love it."),
P("Yeseva One","Josefin Sans","serif-sans","Wedding","A famously charming duo — decorative curves with vintage geometric grace."),
P("Italiana","Karla","serif-sans","Fashion","Italiana's hairline calligraphy against Karla's quirky grotesque warmth. Editorial gold."),
P("Marcellus","Lato","serif-sans","Luxury","Roman inscriptional capitals lend instant heritage; Lato keeps it approachable."),
P("Marcellus","Mulish","serif-sans","Health","Serene classicism with soft modern text — spa and wellness territory."),
P("Cinzel","Raleway","serif-sans","Luxury","Trajan-style capitals over elegant thin sans. Cinematic, ceremonial, premium."),
P("Bodoni Moda","Montserrat","serif-sans","Fashion","The Vogue formula: razor-thin Didone contrast with geometric sans support."),
P("Bodoni Moda","Karla","serif-sans","Magazine","Fashion-mag headlines with an off-beat, human text voice."),
P("Spectral","Karla","serif-sans","Editorial","Two Google-commissioned originals — Spectral's crisp economy with Karla's charm.",{hw:500}),
P("Spectral","IBM Plex Sans","serif-sans","Tech","Screen-native serif and corporate-grade sans. Thoughtful tech writing.",{hw:500}),
P("Newsreader","Inter","serif-sans","Blog","Made for on-screen news text; with Inter it's the modern essay-site standard.",{hw:500}),
P("Literata","Public Sans","serif-sans","News","Google Play Books' serif with the US government's sans — credibility squared."),
P("Source Serif 4","Source Sans 3","serif-sans","Dev","Adobe's open superfamily — drawn to work together, ideal for docs and manuals."),
P("IBM Plex Serif","IBM Plex Sans","serif-sans","Finance","IBM's corporate superfamily. Shared skeleton, effortless hierarchy.",{hw:600}),
P("PT Serif","PT Sans","serif-sans","News","A public-project superfamily built for demanding editorial use."),
P("Alegreya","Alegreya Sans","serif-sans","Education","An award-winning literary superfamily — calligraphic energy in both voices."),
P("Noto Serif","Noto Sans","serif-sans","Education","Google's universal family: unbeatable language coverage, perfectly matched metrics."),
P("Roboto Serif","Roboto","serif-sans","SaaS","The Roboto system, complete — a serif drawn to slot into Android-era UI."),
P("Instrument Serif","Instrument Sans","serif-sans","Portfolio","The current portfolio-site darling: sharp little serif display with a neo-grotesque body."),
P("Young Serif","Inter","serif-sans","Food","Young Serif's chunky 70s warmth over Inter's neutrality — cookbooks and cafés."),
P("Gloock","Hanken Grotesk","serif-sans","Editorial","A modern high-contrast display serif with a Helvetica-warm text partner."),
P("Vollkorn","Lato","serif-sans","Blog","The 'wholemeal' serif — hearty and readable, with Lato keeping things light."),
P("Cardo","Josefin Sans","serif-sans","Editorial","A Typewolf classic: scholarly old-style serif against vintage geometry."),
P("Frank Ruhl Libre","Assistant","serif-sans","News","The Haaretz pairing — dignified serif headlines, clean utilitarian text."),
P("Old Standard TT","Raleway","serif-sans","Education","Nineteenth-century academic flavour, offset by an elegant modern sans."),
P("Sorts Mill Goudy","Lato","serif-sans","Blog","Goudy's bookish charm at display size; Lato stays out of the way.",{hw:400}),
P("Eczar","Work Sans","serif-sans","Editorial","Paired in Google's own type guide — Eczar's fiery personality with Work Sans' calm."),

/* ── SANS HEADINGS × SERIF BODY ─────────────────────────────── */
P("Montserrat","Merriweather","sans-serif","Blog","Possibly the most-recommended pairing on the internet — geometric punch, serif comfort."),
P("Montserrat","Lora","sans-serif","Portfolio","Clean modern headlines with warm, literary body copy."),
P("Montserrat","EB Garamond","sans-serif","Fashion","Contemporary geometry above, renaissance texture below. Editorial contrast done right."),
P("Oswald","Merriweather","sans-serif","News","Tall condensed headlines and sturdy text — a broadsheet in two fonts.",{hw:500}),
P("Oswald","EB Garamond","sans-serif","Editorial","A famous odd couple: industrial condensed sans meets 16th-century garalde.",{hw:500}),
P("Raleway","Merriweather","sans-serif","Blog","Elegant thin display over one of the best screen-reading serifs ever drawn.",{hw:600}),
P("Raleway","Lora","sans-serif","Travel","Airy and graceful — travel journals and photography portfolios.",{hw:600}),
P("Work Sans","Lora","sans-serif","Editorial","A quietly perfect duo: plain grotesque headlines, calligraphic text warmth."),
P("Poppins","Lora","sans-serif","Food","Round geometric friendliness with bookish body text — food blogs live here.",{hw:600}),
P("Poppins","PT Serif","sans-serif","Blog","Poppins' perfect circles against PT's pragmatic serif. Bright but grounded.",{hw:600}),
P("Inter","Lora","sans-serif","Blog","The modern-web default, humanised: UI-crisp headlines, serif reading comfort.",{hw:600}),
P("Inter","Source Serif 4","sans-serif","Dev","Changelog chic — product-grade sans with a serious serif for long reads.",{hw:600}),
P("Inter","Crimson Pro","sans-serif","Education","Neutral interface type over a warm book face. Ideal for courses and essays.",{hw:600}),
P("Lato","Merriweather","sans-serif","Finance","Two workhorses engineered for screens — dependable, legible, trustworthy."),
P("Open Sans","Gelasio","sans-serif","News","Gelasio is metric-compatible with Georgia — instant classic-web credibility."),
P("Nunito Sans","Literata","sans-serif","Health","Soft, rounded headlines with a calm reading serif. Reassuring by design."),
P("League Spartan","Libre Baskerville","sans-serif","Brand","The League of Moveable Type's geometric flagship over Baskerville's timeless text."),
P("Karla","Merriweather","sans-serif","Blog","Karla's slightly-off grotesque charm keeps Merriweather from feeling stiff."),
P("Archivo","Spectral","sans-serif","Magazine","Grotesque headline muscle with a refined, efficient reading serif."),
P("Space Grotesk","Newsreader","sans-serif","Brand","Techy display quirk against editorial serif polish — very now.",{hw:500}),
P("Plus Jakarta Sans","Source Serif 4","sans-serif","Finance","Fintech-favourite geometric sans, balanced by a serif with institutional weight."),
P("DM Sans","Lora","sans-serif","Portfolio","Low-contrast geometric clarity with literary warmth below."),
P("Fira Sans","Merriweather","sans-serif","News","Mozilla's humanist workhorse with the web's great reading serif."),
P("Ubuntu","Lora","sans-serif","Blog","Ubuntu's distinctive curves add personality; Lora does the long-haul reading."),
P("Public Sans","Newsreader","sans-serif","News","Civic-grade neutrality over a news-bred text face. Public-interest publishing."),
P("Quicksand","EB Garamond","sans-serif","Brand","Rounded geometry against renaissance elegance — playful yet cultured.",{hw:600}),
P("Cabin","Old Standard TT","sans-serif","Education","A long-standing community favourite: humanist warmth with academic gravitas."),
P("Heebo","Frank Ruhl Libre","sans-serif","News","An Israeli-press classic in reverse — modern sans headlines, heritage serif text."),
P("Jost","EB Garamond","sans-serif","Architecture","Futura-flavoured geometry with old-style text. Bauhaus meets the book.",{hw:500}),
P("Hanken Grotesk","Source Serif 4","sans-serif","SaaS","Warm grotesque display and a scholarly serif — polished product storytelling."),
P("Figtree","Lora","sans-serif","Travel","Fresh, rounded and legible up top; graceful and unhurried below."),

/* ── SANS × SANS ────────────────────────────────────────────── */
P("Oswald","Open Sans","sans-sans","News","The iconic early-Google-Fonts duo — condensed impact with neutral text.",{hw:500}),
P("Oswald","Lato","sans-sans","Sports","Scoreboard headlines, friendly copy. Still undefeated.",{hw:500}),
P("Montserrat","Open Sans","sans-sans","SaaS","The safe pair of hands. Geometric display, humanist text, zero surprises."),
P("Montserrat","Roboto","sans-sans","Tech","Two giants that simply work — strong hierarchy from weight contrast alone."),
P("Raleway","Open Sans","sans-sans","Portfolio","Thin elegant display over the web's most invisible text face.",{hw:600}),
P("Raleway","Roboto","sans-sans","Agency","Refined display strokes with pragmatic engineering below.",{hw:600}),
P("Poppins","Inter","sans-sans","SaaS","The startup default of the 2020s: geometric charm plus UI-grade legibility.",{hw:600}),
P("Poppins","Open Sans","sans-sans","Education","Bright, approachable and endlessly versatile.",{hw:600}),
P("Poppins","Roboto","sans-sans","Ecommerce","Round display personality with dependable text — conversion-friendly clarity.",{hw:600}),
P("Space Grotesk","Inter","sans-sans","Tech","The AI-startup uniform: quirky grotesque display, neutral system text.",{hw:500}),
P("Space Grotesk","Work Sans","sans-sans","Tech","Two contemporary grotesques, one characterful, one calm.",{hw:500}),
P("Sora","Inter","sans-sans","SaaS","Sora's techy geometry headlines, Inter handles the interface prose.",{hw:600}),
P("Outfit","Inter","sans-sans","SaaS","Crisp geometric display with the web's favourite body sans.",{hw:600}),
P("Outfit","DM Sans","sans-sans","Brand","Two low-contrast geometrics in close harmony — smooth, modern, seamless.",{hw:600}),
P("Plus Jakarta Sans","Inter","sans-sans","Finance","Jakarta's friendly precision over Inter's neutrality — fintech's favourite.",{hw:700}),
P("Manrope","DM Sans","sans-sans","SaaS","Semi-condensed engineering with round geometric text. Quietly excellent.",{hw:800}),
P("Epilogue","Inter","sans-sans","Agency","Sharp contemporary grotesque with reliable text support."),
P("Bricolage Grotesque","Figtree","sans-sans","Brand","Bricolage's editorial swagger over Figtree's easy readability. Fresh but proven."),
P("League Spartan","Work Sans","sans-sans","Agency","Heavy geometric caps and a plain-spoken body — confident studio energy."),
P("Jost","Inter","sans-sans","Brand","Bauhaus geometry for display, modern neutrality for reading.",{hw:500}),
P("Josefin Sans","Lato","sans-sans","Travel","Vintage geometric elegance floating over dependable warmth.",{hw:600}),
P("Quicksand","Nunito","sans-sans","Kids","Everything is round. Friendly, bouncy, impossible to fear.",{hw:600}),
P("Nunito","Nunito Sans","sans-sans","SaaS","Sibling families: rounded display charm with a straightened-out text version."),
P("Rubik","Karla","sans-sans","Tech","Two personalities that rhyme — soft corners meet grotesque quirk.",{hw:600}),
P("Chivo","Roboto","sans-sans","News","Chivo was drawn for Latin-American journalism; Roboto keeps the copy neutral."),
P("Barlow Condensed","Barlow","sans-sans","Sports","One family, two widths — automatic harmony with real hierarchy.",{hw:600}),
P("Exo 2","Roboto","sans-sans","Tech","Sci-fi flavoured display with grounded text. Dashboards and gaming."),
P("Red Hat Display","Red Hat Text","sans-sans","SaaS","A corporate superfamily split by optical size — exactly as intended."),
P("Wix Madefor Display","Wix Madefor Text","sans-sans","Brand","A commissioned superfamily: display and text cuts tuned to each other."),
P("Lexend","Public Sans","sans-sans","Education","Lexend was engineered for reading proficiency — paired with civic-grade neutrality.",{hw:600}),
P("Schibsted Grotesk","Inter","sans-sans","News","Born in a Scandinavian newsroom; Inter carries the paragraphs."),
P("Hanken Grotesk","DM Sans","sans-sans","Portfolio","Warm grotesque meets warm geometric — soft, contemporary, calm."),
P("Urbanist","Inter","sans-sans","Ecommerce","Sleek low-contrast display over utilitarian text. Modern retail."),
P("Figtree","Mulish","sans-sans","Health","Two friendly, open sans faces — approachable and clean."),
P("Archivo","Archivo Narrow","sans-sans","News","Width contrast within one family — dense, editorial, systematic."),

/* ── SERIF × SERIF ──────────────────────────────────────────── */
P("Playfair Display","Lora","serif-serif","Magazine","Display Didone with brushy text serif — rich, layered, literary."),
P("Playfair Display","Source Serif 4","serif-serif","Editorial","Two serifs, two jobs: sparkle at display size, patience at text size."),
P("Fraunces","Literata","serif-serif","Magazine","Soft wonk over book-grade text. A food-magazine dream.",{hw:600}),
P("Cormorant Garamond","EB Garamond","serif-serif","Luxury","Garamond twice — once as a whisper-thin display, once as sturdy text.",{hw:600}),
P("DM Serif Display","Crimson Pro","serif-serif","Blog","Sharp Didone headlines with a gentle, bookish reading face."),
P("Libre Caslon Display","Libre Caslon Text","serif-serif","Editorial","A true optical pair — Caslon cut separately for headlines and paragraphs."),
P("Bodoni Moda","Cormorant Garamond","serif-serif","Fashion","Maximum refinement: Didone edge over garalde grace. Handle with taste."),
P("Yeseva One","Crimson Text","serif-serif","Food","A beloved community pairing — decorative warmth with classic text."),
P("Cinzel","EB Garamond","serif-serif","Event","Roman capitals and renaissance text — theatre programmes, galas, wine."),
P("Marcellus","Cormorant Garamond","serif-serif","Wedding","Inscriptional calm over delicate elegance. Invitation-ready.",{hw:600}),
P("Newsreader","Literata","serif-serif","News","Two modern text serifs built for screens — quiet, credible, comfortable.",{hw:500}),
P("Instrument Serif","Crimson Pro","serif-serif","Portfolio","Trendy sharp display serif with an easy-going book face below."),
P("Gloock","Newsreader","serif-serif","Magazine","Contemporary contrast up top, newsprint patience below."),
P("Lora","Merriweather","serif-serif","Blog","Two screen-first serifs a step apart in flavour — subtle, cohesive depth.",{hw:600}),
P("Old Standard TT","Cardo","serif-serif","Education","Scholarly through and through — journals, classics departments, footnotes."),

/* ── DISPLAY ────────────────────────────────────────────────── */
P("Bebas Neue","Open Sans","display","Sports","The poster classic. All-caps condensed impact, neutral supporting text."),
P("Bebas Neue","Montserrat","display","Agency","Loud meets clean — a studio staple for a decade."),
P("Bebas Neue","Lato","display","Event","Billboard energy with warm, humanist copy."),
P("Anton","Roboto","display","Sports","Maximum headline tonnage; Roboto keeps the paragraphs practical."),
P("Anton","Work Sans","display","Music","Gig-poster weight with a level-headed text partner."),
P("Archivo Black","Roboto","display","Agency","Brutalist black grotesque over system-grade text. Swiss-poster energy."),
P("Archivo Black","Archivo","display","Brand","One family, maximum contrast — black display, regular text, total cohesion."),
P("Abril Fatface","Lato","display","Magazine","A fat-face Didone straight off a Victorian playbill, tamed by friendly text."),
P("Abril Fatface","Poppins","display","Food","Rich, syrupy display with round geometric body — dessert-menu perfect."),
P("Alfa Slab One","Open Sans","display","Food","Heavy slab charm — bakeries, burgers, and anything hearty."),
P("Ultra","Open Sans","display","Brand","Wood-type Americana with quiet modern support."),
P("Shrikhand","Poppins","display","Brand","Juicy Gujarati-inspired display with matching Indian-foundry geometry. Pure joy."),
P("Calistoga","Lato","display","Food","Soft-serve diner display; Lato keeps the menu legible."),
P("Fjalla One","Open Sans","display","News","Condensed and stern up top, open and calm below — classic pairing-site royalty."),
P("Staatliches","Rubik","display","Event","Poster caps with rounded text — festivals and exhibitions."),
P("Righteous","Karla","display","Music","70s-tinged display groove against Karla's grotesque charm."),
P("Fredoka","Nunito","display","Kids","Round display, round text, zero sharp edges anywhere.",{hw:600}),
P("Baloo 2","Nunito Sans","display","Kids","A bouncy heavyweight from India's Ek Type with clean supporting text."),
P("Teko","Open Sans","display","Sports","Scoreboard-condensed display over the web's most neutral body.",{hw:600}),
P("Yanone Kaffeesatz","Open Sans","display","Food","The café classic — literally named after coffee grounds."),
P("Bungee","Open Sans","display","Event","Signage-inspired vertical-ready display. Street festivals, arcades, fun."),
P("Monoton","Montserrat","display","Music","A neon marquee in font form. One line only — then hand off to Montserrat."),
P("Krona One","Inter","display","Tech","Wide, techy display presence with clean interface text."),
P("Poiret One","Montserrat","display","Fashion","Art-deco hairline geometry over modern structure. Gatsby-approved.",{hw:400}),
P("Julius Sans One","EB Garamond","display","Wedding","Hairline caps and renaissance text — formal without being fussy.",{hw:400}),
P("Six Caps","EB Garamond","display","Editorial","Skyscraper-condensed caps against classical text — high-fashion editorial tension."),
P("Rozha One","Poppins","display","Magazine","A Devanagari-rooted fat Didone with round geometric support."),
P("Passion One","Open Sans","display","Sports","Rounded heavyweight headlines, sensible body. Match-day ready."),
P("Unbounded","Manrope","display","Tech","Polkadot's expanded display face — futurist headlines, engineered text."),
P("Syne","Inter","display","Agency","Art-school weirdness in the display sizes, dead-straight text below."),

/* ── SLAB ───────────────────────────────────────────────────── */
P("Roboto Slab","Roboto","slab","Tech","The Roboto system with slab serifs — mechanical harmony, free hierarchy."),
P("Arvo","Lato","slab","Blog","One of the original Google Fonts pairings — geometric slab with humanist text."),
P("Zilla Slab","Inter","slab","Tech","Mozilla's brand slab with modern UI text. Open-source spirit."),
P("Bitter","Raleway","slab","Blog","Screen-tuned slab warmth against thin elegant display — a fontpair classic."),
P("Domine","Open Sans","slab","News","Domine was drawn for news body text; flipped to headlines it anchors a page."),
P("Rokkitt","Lato","slab","Agency","Confident slab geometry with easy-going copy."),
P("Crete Round","ABeeZee","slab","Education","Soft Italian slab with a schoolbook sans — gentle and studious.",{hw:400}),
P("Aleo","Open Sans","slab","Education","Contemporary semi-rounded slab over the universal body."),
P("Josefin Slab","Josefin Sans","slab","Brand","Twin families by the same designer — vintage geometry in two flavours.",{hw:600}),
P("Patua One","Lato","slab","Event","Poster-grade slab display with dependable text support."),

/* ── MONO ───────────────────────────────────────────────────── */
P("Space Grotesk","Space Mono","mono","Tech","Space Grotesk was literally derived from Space Mono — a genetic match.",{hw:500}),
P("IBM Plex Mono","IBM Plex Sans","mono","Dev","The Plex superfamily's terminal voice for headlines, sans for prose."),
P("JetBrains Mono","Inter","mono","Dev","The developer-tools standard: code-native display with UI-grade text."),
P("Fira Code","Fira Sans","mono","Dev","Mozilla's family, with ligature-famous code cousin. Docs done right."),
P("Source Code Pro","Source Sans 3","mono","Dev","Adobe's open trio at work — mono and sans drawn to the same skeleton."),
P("Roboto Mono","Roboto","mono","Dev","System-family coherence with terminal flavour on top."),
P("DM Mono","DM Sans","mono","Portfolio","DM Sans' typewriter sibling — lowercase mono headlines feel effortlessly cool.",{hw:500}),
P("Space Mono","Work Sans","mono","Portfolio","Retro-futurist mono display against a plain, warm grotesque."),
P("Inconsolata","Open Sans","mono","Dev","A beloved humanist mono with the web's default body."),
P("Courier Prime","Lora","mono","Editorial","The screenplay font, upgraded — typewriter romance with literary text."),
P("Martian Mono","Inter","mono","Tech","A grotesque-flavoured mono for dev-tool landing pages. Sharp and current."),
P("Azeret Mono","Manrope","mono","Brand","Displayful mono with engineered sans — design-studio coded.",{hw:800}),
P("Chivo Mono","Chivo","mono","Finance","Chivo in two voices — data tables and dashboards feel native."),
P("Red Hat Mono","Red Hat Text","mono","Dev","Corporate open-source coherence, terminal to paragraph."),
P("Spline Sans Mono","Spline Sans","mono","Dev","A UI-first pair built together for product and code."),
P("Geist Mono","Geist","mono","Dev","Vercel's family, now on Google Fonts — the definitive dev-brand look."),
P("Ubuntu Mono","Ubuntu","mono","Dev","The Ubuntu system family — distinctive, warm, deeply tested."),

/* ── SCRIPT & HANDWRITTEN ───────────────────────────────────── */
P("Caveat","Open Sans","script","Blog","Margin-note handwriting for headings, clean text for everything else."),
P("Pacifico","Quicksand","script","Food","Surf-shop brush script with round geometric text — ice-cream-van happy."),
P("Dancing Script","Lato","script","Event","Lively casual script over neutral warmth. Invitations without stiffness."),
P("Great Vibes","EB Garamond","script","Wedding","Formal copperplate flourish with renaissance text — the classic invitation."),
P("Sacramento","Montserrat","script","Fashion","A thin monoline script against geometric structure — chic and breezy."),
P("Parisienne","Montserrat","script","Wedding","Romantic French casualness with a dependable modern base."),
P("Amatic SC","Josefin Sans","script","Food","The chalkboard-menu duo — hand-drawn condensed caps with vintage geometry."),
P("Shadows Into Light","Open Sans","script","Travel","Journal-entry handwriting over quiet text. Scrapbooks and travelogues."),
P("Satisfy","Karla","script","Brand","Relaxed brush script with grotesque charm — crafty but composed."),
P("Kalam","Mukta","script","Education","Two Indian Type Foundry faces — handwritten warmth with clean Devanagari-ready text."),
P("Patrick Hand","Nunito","script","Kids","Neat, cheerful handwriting with soft rounded text. Storybook stuff."),
P("Yellowtail","Lato","script","Food","A 50s diner brush script — add Lato and you can smell the pancakes."),
];
